import {
  SignIn,
  SignInButton,
  SignOutButton,
  SignUp,
  useUser,
} from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { NavBar } from "~/components/navbar";

import { RouterOutputs, api } from "~/utils/api";

// type PostWithUser = RouterOutputs["posts"]["getAll"][number];
// const PostView = (props: PostWithUser) => {
//   const { post } = props;
//   return (
//     <div key={post.id} className="border-b border-slate-400 p-8">
//       {post.content}
//     </div>
//   );
// };

const Home: NextPage = () => {
  const user = useUser();
  const hello = api.example.hello;
  console.log(hello);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <header>
          <NavBar />
          <div>content</div>
          <div>content</div>
          <div>content</div>
          <div>content</div>
        </header>
      </main>
    </>
  );
};

export default Home;
