import { type NextPage } from "next";
import Head from "next/head";
import { NavBar } from "~/components/navbar";

import { RouterOutputs, api } from "~/utils/api";

const Options: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className="flex justify-center">
        <div>Options page</div>
      </main>
    </>
  );
};

export default Options;
